### ISSUE TITLE
Crash when I try to use Markdown at RichEditor

### ISSUE THREAD

**Issue by cheprasov** [sanity-io/sanity-plugin-markdown#8]
Thanks a lot for the plugin.
It works good when I use the markdown as separate field 
<img width="670" alt="Screenshot 2021-05-18 at 16 43 43" src="https://user-images.githubusercontent.com/4299922/118682301-3aba6a80-b7f8-11eb-9c4a-7d1fad8fea08.png">

But the app crash when I try to use the Markdown at RichEditor.

```
    {
      name: 'body',
      title: 'Body content',
      type: 'array',
      fieldset: 'main',
      of: [
        {
          type: 'block',
        },
        {
          title: 'Table',
          type: 'table',
        },
        {
          title: 'Markdown',
          type: 'markdown',
        },
      ],
    },
```

<img width="698" alt="Screenshot 2021-05-18 at 16 37 47" src="https://user-images.githubusercontent.com/4299922/118681547-93d5ce80-b7f7-11eb-89e0-c77b7b1258be.png">
<img width="586" alt="Screenshot 2021-05-18 at 16 37 54" src="https://user-images.githubusercontent.com/4299922/118681556-9506fb80-b7f7-11eb-911b-b94bf30905dc.png">
<img width="834" alt="Screenshot 2021-05-18 at 16 38 30" src="https://user-images.githubusercontent.com/4299922/118681565-959f9200-b7f7-11eb-80e8-5cb0dd6fdc73.png">

```
Stack trace:
Error: Cannot set value of an object to a non-object
    at apply (/static/js/app.bundle.js:283385:15)
    at applyPatch (/static/js/app.bundle.js:85492:32)
    at _apply (/static/js/app.bundle.js:85499:13)
    at Array.reduce (<anonymous>)
    at applyAll (/static/js/app.bundle.js:85479:18)
    at handleChange (/static/js/app.bundle.js:282934:41)
    at handleChange (/static/js/app.bundle.js:283622:36)
    at Object.onChange (/static/js/app.bundle.js:32552:7)
    at http://localhost:3333/static/js/app.bundle.js:221927:13
    at commitHookEffectListMount (/static/js/vendor.bundle.js:22468:26)
Component stack:
    in Editor (created by FormBuilderInputInner)
    in ChangeIndicatorProvider (created by FormBuilderInputInner)
    in div (created by FormBuilderInputInner)
    in FormBuilderInputInner (created by FormBuilderInput)
    in FormBuilderInput (created by DefaultObjectEditing)
    in div (created by ForwardRef(RegionsWithIntersections))
    in div (created by ForwardRef(RegionsWithIntersections))
    in ForwardRef(RegionsWithIntersections) (created by StickyOverlay)
    in StickyOverlay (created by OverlayEnabled)
    in Tracker (created by OverlayEnabled)
    in OverlayEnabled (created by DefaultObjectEditing)
    in div (created by DefaultDialogChildren)
    in div (created by ForwardRef(ScrollContainer))
    in ForwardRef(ScrollContainer) (created by DefaultDialogChildren)
    in div (created by DefaultDialogChildren)
    in div (created by DefaultDialogChildren)
    in div (created by ContainerQuery)
    in ContainerQuery (created by DefaultDialogChildren)
    in DefaultDialogChildren (created by DefaultDialog)
    in LayerProvider (created by LegacyLayerProvider)
    in LegacyLayerProvider (created by DefaultDialog)
    in Portal (created by DefaultDialog)
    in DefaultDialog (created by DefaultObjectEditing)
    in DefaultObjectEditing (created by EditObject)
    in EditObject (created by PortableTextInput)
    in div (created by PortableTextInput)
    in PortableTextInput (created by ForwardRef(PortableTextInput))
    in PortableTextEditor (created by ForwardRef(PortableTextInput))
    in ForwardRef(PortableTextInput) (created by PortableTextInputWithFocusAndBlur)
    in div (created by DefaultFormField)
    in div (created by DefaultFormField)
    in DefaultFormField (created by PortableTextInputWithFocusAndBlur)
    in PortableTextInputWithFocusAndBlur (created by withPatches(PortableTextInputWithFocusAndBlur))
    in withPatches(PortableTextInputWithFocusAndBlur) (created by FormBuilderInputInner)
    in ChangeIndicatorProvider (created by FormBuilderInputInner)
    in div (created by FormBuilderInputInner)
    in FormBuilderInputInner (created by FormBuilderInput)
    in FormBuilderInput (created by Tabs)
    in div (created by Tabs)
    in div (created by Tabs)
    in div (created by Tabs)
    in Tabs (created by withDocument(Tabs))
    in withDocument(Tabs) (created by FormBuilderInputInner)
    in ChangeIndicatorProvider (created by FormBuilderInputInner)
    in div (created by FormBuilderInputInner)
    in FormBuilderInputInner (created by FormBuilderInput)
    in FormBuilderInput (created by Field)
    in div (created by Field)
    in Field (created by ObjectInput)
    in div (created by ObjectInput)
    in div (created by ObjectInput)
    in ObjectInput (created by FormBuilderInputInner)
    in ChangeIndicatorProvider (created by FormBuilderInputInner)
    in div (created by FormBuilderInputInner)
    in FormBuilderInputInner (created by FormBuilderInput)
    in FormBuilderInput (created by SanityFormBuilder)
    in FormBuilderContext (created by SanityFormBuilderContext)
    in SanityFormBuilderContext (created by SanityFormBuilder)
    in SanityFormBuilder
    in form
    in Unknown (created by FormView)
    in div (created by ForwardRef(RegionsWithIntersections))
    in div (created by ForwardRef(RegionsWithIntersections))
    in ForwardRef(RegionsWithIntersections) (created by StickyOverlay)
    in StickyOverlay (created by OverlayEnabled)
    in Tracker (created by OverlayEnabled)
    in OverlayEnabled (created by FormView)
    in div (created by FormView)
    in FormView (created by DocumentPanel)
    in div (created by ForwardRef(ScrollContainer))
    in ForwardRef(ScrollContainer) (created by DocumentPanel)
    in div (created by DocumentPanel)
    in BoundaryElementProvider (created by DocumentPanel)
    in PortalProvider (created by DocumentPanel)
    in div (created by styled.div)
    in styled.div (created by Box)
    in Box (created by Styled(Box))
    in Styled(Box) (created by Card)
    in Ge (created by ThemeProvider)
    in ThemeProvider (created by ThemeColorProvider)
    in ThemeColorProvider (created by Card)
    in Card (created by DocumentPanel)
    in DocumentPanel (created by DocumentPane)
    in div (created by DocumentPane)
    in div (created by ForwardRef(ScrollContainer))
    in ForwardRef(ScrollContainer) (created by EnabledChangeConnectorRoot)
    in Tracker (created by EnabledChangeConnectorRoot)
    in EnabledChangeConnectorRoot (created by DocumentPane)
    in DialogProvider (created by DocumentPane)
    in div (created by KeyboardShortcutResponder)
    in KeyboardShortcutResponder (created by GetHookCollectionState)
    in GetHookCollectionState (created by RenderActionCollectionState)
    in RenderActionCollectionState
    in Unknown (created by DocumentPane)
    in LayerProvider (created by LegacyLayerProvider)
    in LegacyLayerProvider (created by DocumentPane)
    in DocumentPane (created by DocumentPaneProvider)
    in DocumentHistoryProvider (created by DocumentPaneProvider)
    in DocumentPaneProvider
    in StreamingComponent
    in StreamingComponent (created by Context.Consumer)
    in WithInitialValueWrapper (created by DeskToolPane)
    in DeskToolPane (created by DeskToolPanes)
    in SplitPaneWrapper (created by DeskToolPanes)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in div (created by Pane)
    in Pane (created by SplitPane)
    in div (created by SplitPane)
    in SplitPane (created by PanesSplitController)
    in div (created by PanesSplitController)
    in PanesSplitController (created by DeskToolPanes)
    in PortalProvider (created by DeskToolPanes)
    in div (created by DeskToolPanes)
    in DeskToolPanes (created by DeskTool)
    in DeskTool (created by withRouter(DeskTool))
    in withRouter(DeskTool) (created by DeskToolPaneStateSyncer)
    in DeskToolPaneStateSyncer (created by DeskTool)
    in DeskToolFeaturesProvider (created by DeskTool)
    in DeskTool (created by RenderTool)
    in RenderTool (created by SchemaErrorReporter)
    in RouteScope (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in SchemaErrorReporter (created by DefaultLayout)
    in DefaultLayout (created by withRouter(DefaultLayout))
    in withRouter(DefaultLayout) (created by DefaultLayoutRoot)
    in RouterProvider (created by DefaultLayoutRoot)
    in LoginWrapper (created by DefaultLayoutRoot)
    in DefaultLayoutRoot (created by AppProvider)
    in div (created by styled.div)
    in styled.div (created by Box)
    in Box (created by Styled(Box))
    in Styled(Box) (created by Card)
    in Ge (created by ThemeProvider)
    in ThemeProvider (created by ThemeColorProvider)
    in ThemeColorProvider (created by Card)
    in Card (created by Styled(Card))
    in Styled(Card) (created by AppProvider)
    in SnackbarProvider (created by AppProvider)
    in ToastProvider (created by AppProvider)
    in LayerProvider (created by AppProvider)
    in PortalProvider (created by AppProvider)
    in UserColorManagerProvider (created by AppProvider)
    in AppProvider (created by SanityRoot)
    in Ge (created by ThemeProvider)
    in ThemeProvider (created by SanityRoot)
    in ZIndexProvider (created by SanityRoot)
    in SanityRoot
    in AppContainer
```

**Comment by runeb** [comment]
Thank you for the report @cheprasov .I will take a look at this next week. No reason it should not work embedded in portable text, or any other place, so positive we can fix this.

**Comment by cheprasov** [comment]
Thanks a lot :)

**Comment by cheprasov** [comment]
Hi @runeb 
How are you today? Do you have time to check the issue this week?

**Comment by runeb** [comment]
Hello @cheprasov . You can solve this by wrapping your value in an object

```
{
  type: "object",
  name: "embeddedMarkdown",
  fields: [
    {
      type: "markdown",
      name: "value"
    }
  ]
}
```

and include that in your portable text instead.

**Comment by runeb** [comment]
Closing this. While its a valid use case, it is solvable with schema definitions.

**Comment by cheprasov** [comment]
Thanks a lot :)

**Comment by rohanrajpal** [comment]
> Hello @cheprasov . You can solve this by wrapping your value in an object
> 
> ```
> {
>   type: "object",
>   name: "embeddedMarkdown",
>   fields: [
>     {
>       type: "markdown",
>       name: "value"
>     }
>   ]
> }
> ```
> 
> and include that in your portable text instead.

This should actually be in the docs somewehre
